server:
  port: ${SERVER_PORT:8082}

spring:
  application:
    name: ms-productos

  datasource:
    url: jdbc:postgresql://localhost:5432/usuarios_db
    username: admin
    password: admin123
    driver-class-name: org.postgresql.Driver

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  security:
    oauth2:
      resourceserver:
        jwt:
          tenant-id: e5372bf0-c5e3-4286-887c-79069f209c1f
          client-id: c4dba118-062a-49e8-a1d9-ae2ee29e7716

logging:
  level:
    org.springframework.security: DEBUG
