server:
  port: ${SERVER_PORT:8083}

spring:
  application:
    name: ms-carrito

  datasource:
    url: jdbc:postgresql://localhost:5432/usuarios_db
    username: admin
    password: admin123
    driver-class-name: org.postgresql.Driver

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  security:
    oauth2:
      resourceserver:
        jwt:
          tenant-id:
          client-id:

logging:
  level:
    org.springframework.security: DEBUG

resilience4j:
  circuitbreaker:
    instances:
      msProductos:
        sliding-window-size: 10
        failure-rate-threshold: 50
        wait-duration-in-open-state: 10s
        permitted-number-of-calls-in-half-open-state: 3